# Generated by Django 3.1.8 on 2021-04-09 21:50

import uuid

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('slogan', models.TextField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyUserPermissions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_create_jobs', models.BooleanField(default=False)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_user_permissions',
                                   to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('auth0_id', models.TextField()),
                ('linkedin_id', models.TextField()),
                ('github_username', models.TextField(blank=True, default='')),
                ('is_developer', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('companies', models.ManyToManyField(through='api.CompanyUserPermissions', to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companyuserpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='company_user_permissions', to='api.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(through='api.CompanyUserPermissions', to='api.User'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('is_developer', False), models.Q(('is_developer', True),
                                                                                               models.Q(_negated=True,
                                                                                                        github_username__exact='')),
                                                             _connector='OR'), name='required_developer_fields'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, github_username__exact=''),
                                               fields=('github_username',), name='unique_github_username'),
        ),
    ]
