# Generated by Django 3.1.8 on 2021-04-11 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyUserPermissions',
            new_name='CompanyPosition',
        ),
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions',
                                    to='api.company'),
        ),
        migrations.AlterField(
            model_name='companyposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions',
                                    to='api.user'),
        ),
    ]
