# Generated by Django 3.1.8 on 2021-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210411_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyposition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
