# Generated by Django 3.1.8 on 2021-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20210411_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyposition',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyposition',
            name='end_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyposition',
            name='start_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
