# Generated by Django 3.1.8 on 2021-05-04 04:34

import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_auto_20210503_2020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_id',
        ),
        migrations.AddField(
            model_name='user',
            name='finished_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_username',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list,
                                                            size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list,
                                                            size=None),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, linkedin_username__exact=''),
                                               fields=('linkedin_username',), name='unique_linkedin_username'),
        ),
    ]
