# Generated by Django 3.1.9 on 2021-05-06 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_companyposition_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cultures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list,
                                                            size=None),
        ),
    ]
