# Generated by Django 3.1b1 on 2020-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField(max_length=400)),
                ('priority', models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], max_length=1)),
            ],
            options={
                'verbose_name': 'The Question',
                'verbose_name_plural': "People's Questions",
            },
        ),
    ]
